version: '3.1'
services:
    webserver:
      image: nginx:alpine
      container_name: recluit-webserver
      working_dir: /app
      volumes:
          - .:/app
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - '8000:80'
      depends_on:
        - php

    postgresql:
      image: postgres:11-alpine
      restart: always
      environment:
        POSTGRES_DB: ${DATABASE}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
      ports:
        - '5432:5432'
      volumes:
        - ./pgdata:/var/lib/postgresql/data
        - ./database/recluit.sql:/docker-entrypoint-initdb.d/init.sql

    php:
      build:
        context: .
        dockerfile: docker/php/Dockerfile
      working_dir: /app
      volumes:
        - .:/app
      environment:
        DB_HOST: ${DB_HOST}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DATABASE}
        DB_PORT: ${DB_PORT}
      links:
        - postgresql
      depends_on:
        - postgresql