version: '3.1'
services:
    webserver:
      image: nginx:alpine
      container_name: recluit-webserver
      working_dir: /app
      volumes:
          - .:/app
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - '8000:80'
      depends_on:
        - php

    postgresql:
      image: postgres:11-alpine
      restart: always
      environment:
        POSTGRES_DB: ${database_name}
        POSTGRES_USER: ${database_user}
        POSTGRES_PASSWORD: ${database_password}
      ports:
        - '5432:5432'
      volumes:
        - ./pgdata:/var/lib/postgresql/data
        - ./database/atenas.sql:/docker-entrypoint-initdb.d/init.sql

    php:
      build:
        context: .
        dockerfile: docker/php/Dockerfile
      working_dir: /app
      volumes:
        - .:/app
      environment:
        DB_HOST: postgresql
        DB_USER: admin
        DB_PASSWORD: '00000000'
        DB_NAME: atenas
        DB_PORT: '5000'
      links:
        - postgresql
      depends_on:
        - postgresql